replicaCount: 2

image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/node-microservice
  pullPolicy: Always
  tag: latest

serviceAccount:
  create: true
  name: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

ingress:
  enabled: false
  className: ""
  hosts:
    - host: nodeapp.example.com
      paths:
        - path: /
          pathType: Prefix