apiVersion: v1
kind: Pod
metadata:
  name: jenkins-nodejs-agent
spec:
  containers:
    - name: nodejs
      image: node:20         # Node.js image with npm
      command:
        - cat                # keeps the container alive
      tty: true
  restartPolicy: Never