pipeline {

    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jenkins-agent
    image: jenkins/inbound-agent:latest
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    volumeMounts:
      - name: kaniko-secret
        mountPath: /secret
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred   # your Docker/ECR credentials
"""
        }
    }

    environment {
        AWS_REGION = 'ap-south-1'
        ECR_REPO = '891970965031.dkr.ecr.ap-south-1.amazonaws.com/node-microservice'
    }

    stages {

        stage('Clone Repo') {
            steps {
                git 'https://github.com/chilkamollasravanthi999/eks-node-microservice.git'
            }
        }

        stage('Build & Push Image') {
            steps {
                container('kaniko') {
                    sh """
                    /kaniko/executor \
                        --context \$WORKSPACE \
                        --dockerfile \$WORKSPACE/Dockerfile \
                        --destination \$ECR_REPO:latest \
                        --docker-config /secret
                    """
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh 'helm upgrade --install nodeapp helm/nodeapp'
            }
        }

    }

}